// <auto-generated />
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using GriesserPresuSync.Controllers;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using static GriesserPresuSync.Controllers.MiGriesserMallorquinas;

namespace GriesserPresuSync.Migrations
{
    // ========================================
    // MiGriesserMallorquinas_LineasRepository.cs
    // IG_GriesserSyncMallor2_Lineas - Tabla Segundo Nivel
    // ========================================

    public class MiGriesserMallorquinas_LineasRepository
    {
        private readonly string _connectionString;

        public MiGriesserMallorquinas_LineasRepository(string connectionString)
        {
            _connectionString = connectionString;
        }

        public async Task<List<(string IdLineaPadre, int IdLinea)>> GetAllLineasPksAsync()
        {
            var pks = new List<(string, int)>();
            const string query = "SELECT IdLineaPadre, IdLinea FROM IG_GriesserSyncMallor2_Lineas";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                await connection.OpenAsync();
                using (var reader = await command.ExecuteReaderAsync())
                {
                    while (await reader.ReadAsync())
                    {
                        if (!reader.IsDBNull(0) && !reader.IsDBNull(1))
                        {
                            pks.Add((reader.GetString(0), reader.GetInt32(1)));
                        }
                    }
                }
            }
            return pks;
        }

        public async Task InsertLineaAsync(IG_GriesserSyncMallor2_Lineas linea)
        {
            const string query = @"INSERT INTO IG_GriesserSyncMallor2_Lineas (
                IdLineaPadre, IdLinea, pos, id_mallorquina_tipo, cod_mallorquina_tipo, id_mallorquina_modelo,
                cod_mallorquina_modelo, ancho_hueco, alto_hueco, id_mallorquina_esquema, cod_mallorquina_esquema,
                id_mallorquina_tipologia_instalacion, cod_mallorquina_tipologia_instalacion, motorizado,
                ancho_hoja, alto_hoja, precio_por_hoja, num_hojas, precio_herraje, precio_incrementos,
                precio_automatismos, units, total, id_automatismo_marca, cod_automatismo_marca,
                id_automatismo_receptor, cod_automatismo_receptor, precio_receptor, precio_mandos
            ) VALUES (
                @IdLineaPadre, @IdLinea, @pos, @id_mallorquina_tipo, @cod_mallorquina_tipo, @id_mallorquina_modelo,
                @cod_mallorquina_modelo, @ancho_hueco, @alto_hueco, @id_mallorquina_esquema, @cod_mallorquina_esquema,
                @id_mallorquina_tipologia_instalacion, @cod_mallorquina_tipologia_instalacion, @motorizado,
                @ancho_hoja, @alto_hoja, @precio_por_hoja, @num_hojas, @precio_herraje, @precio_incrementos,
                @precio_automatismos, @units, @total, @id_automatismo_marca, @cod_automatismo_marca,
                @id_automatismo_receptor, @cod_automatismo_receptor, @precio_receptor, @precio_mandos
            )";

            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", linea.IdLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", linea.IdLinea);
                command.Parameters.AddWithValue("@pos", (object?)linea.pos ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_tipo", (object?)linea.id_mallorquina_tipo ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_tipo", (object?)linea.cod_mallorquina_tipo ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_modelo", (object?)linea.id_mallorquina_modelo ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_modelo", (object?)linea.cod_mallorquina_modelo ?? DBNull.Value);
                command.Parameters.AddWithValue("@ancho_hueco", (object?)linea.ancho_hueco ?? DBNull.Value);
                command.Parameters.AddWithValue("@alto_hueco", (object?)linea.alto_hueco ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_esquema", (object?)linea.id_mallorquina_esquema ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_esquema", (object?)linea.cod_mallorquina_esquema ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_tipologia_instalacion", (object?)linea.id_mallorquina_tipologia_instalacion ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_tipologia_instalacion", (object?)linea.cod_mallorquina_tipologia_instalacion ?? DBNull.Value);
                command.Parameters.AddWithValue("@motorizado", (object?)linea.motorizado ?? DBNull.Value);
                command.Parameters.AddWithValue("@ancho_hoja", (object?)linea.ancho_hoja ?? DBNull.Value);
                command.Parameters.AddWithValue("@alto_hoja", (object?)linea.alto_hoja ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_por_hoja", (object?)linea.precio_por_hoja ?? DBNull.Value);
                command.Parameters.AddWithValue("@num_hojas", (object?)linea.num_hojas ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_herraje", (object?)linea.precio_herraje ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_incrementos", (object?)linea.precio_incrementos ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_automatismos", (object?)linea.precio_automatismos ?? DBNull.Value);
                command.Parameters.AddWithValue("@units", (object?)linea.units ?? DBNull.Value);
                command.Parameters.AddWithValue("@total", (object?)linea.total ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_automatismo_marca", (object?)linea.id_automatismo_marca ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_automatismo_marca", (object?)linea.cod_automatismo_marca ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_automatismo_receptor", (object?)linea.id_automatismo_receptor ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_automatismo_receptor", (object?)linea.cod_automatismo_receptor ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_receptor", (object?)linea.precio_receptor ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_mandos", (object?)linea.precio_mandos ?? DBNull.Value);

                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task<bool> ExistsLineaAsync(string idLineaPadre, int idLinea)
        {
            const string query = "SELECT COUNT(1) FROM IG_GriesserSyncMallor2_Lineas WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", idLinea);
                await connection.OpenAsync();
                var count = (int)await command.ExecuteScalarAsync();
                return count > 0;
            }
        }

        public async Task UpdateLineaAsync(IG_GriesserSyncMallor2_Lineas linea)
        {
            const string query = @"UPDATE IG_GriesserSyncMallor2_Lineas SET 
                pos = @pos,
                id_mallorquina_tipo = @id_mallorquina_tipo,
                cod_mallorquina_tipo = @cod_mallorquina_tipo,
                id_mallorquina_modelo = @id_mallorquina_modelo,
                cod_mallorquina_modelo = @cod_mallorquina_modelo,
                ancho_hueco = @ancho_hueco,
                alto_hueco = @alto_hueco,
                id_mallorquina_esquema = @id_mallorquina_esquema,
                cod_mallorquina_esquema = @cod_mallorquina_esquema,
                id_mallorquina_tipologia_instalacion = @id_mallorquina_tipologia_instalacion,
                cod_mallorquina_tipologia_instalacion = @cod_mallorquina_tipologia_instalacion,
                motorizado = @motorizado,
                ancho_hoja = @ancho_hoja,
                alto_hoja = @alto_hoja,
                precio_por_hoja = @precio_por_hoja,
                num_hojas = @num_hojas,
                precio_herraje = @precio_herraje,
                precio_incrementos = @precio_incrementos,
                precio_automatismos = @precio_automatismos,
                units = @units,
                total = @total,
                id_automatismo_marca = @id_automatismo_marca,
                cod_automatismo_marca = @cod_automatismo_marca,
                id_automatismo_receptor = @id_automatismo_receptor,
                cod_automatismo_receptor = @cod_automatismo_receptor,
                precio_receptor = @precio_receptor,
                precio_mandos = @precio_mandos
            WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea";

            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", linea.IdLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", linea.IdLinea);
                command.Parameters.AddWithValue("@pos", (object?)linea.pos ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_tipo", (object?)linea.id_mallorquina_tipo ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_tipo", (object?)linea.cod_mallorquina_tipo ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_modelo", (object?)linea.id_mallorquina_modelo ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_modelo", (object?)linea.cod_mallorquina_modelo ?? DBNull.Value);
                command.Parameters.AddWithValue("@ancho_hueco", (object?)linea.ancho_hueco ?? DBNull.Value);
                command.Parameters.AddWithValue("@alto_hueco", (object?)linea.alto_hueco ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_esquema", (object?)linea.id_mallorquina_esquema ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_esquema", (object?)linea.cod_mallorquina_esquema ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_mallorquina_tipologia_instalacion", (object?)linea.id_mallorquina_tipologia_instalacion ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_mallorquina_tipologia_instalacion", (object?)linea.cod_mallorquina_tipologia_instalacion ?? DBNull.Value);
                command.Parameters.AddWithValue("@motorizado", (object?)linea.motorizado ?? DBNull.Value);
                command.Parameters.AddWithValue("@ancho_hoja", (object?)linea.ancho_hoja ?? DBNull.Value);
                command.Parameters.AddWithValue("@alto_hoja", (object?)linea.alto_hoja ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_por_hoja", (object?)linea.precio_por_hoja ?? DBNull.Value);
                command.Parameters.AddWithValue("@num_hojas", (object?)linea.num_hojas ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_herraje", (object?)linea.precio_herraje ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_incrementos", (object?)linea.precio_incrementos ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_automatismos", (object?)linea.precio_automatismos ?? DBNull.Value);
                command.Parameters.AddWithValue("@units", (object?)linea.units ?? DBNull.Value);
                command.Parameters.AddWithValue("@total", (object?)linea.total ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_automatismo_marca", (object?)linea.id_automatismo_marca ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_automatismo_marca", (object?)linea.cod_automatismo_marca ?? DBNull.Value);
                command.Parameters.AddWithValue("@id_automatismo_receptor", (object?)linea.id_automatismo_receptor ?? DBNull.Value);
                command.Parameters.AddWithValue("@cod_automatismo_receptor", (object?)linea.cod_automatismo_receptor ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_receptor", (object?)linea.precio_receptor ?? DBNull.Value);
                command.Parameters.AddWithValue("@precio_mandos", (object?)linea.precio_mandos ?? DBNull.Value);

                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task DeleteLineasByPresupuestoAsync(string idLineaPadre)
        {
            const string query = "DELETE FROM IG_GriesserSyncMallor2_Lineas WHERE IdLineaPadre = @IdLineaPadre";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task DeleteLineaAsync(string idLineaPadre, int idLinea)
        {
            const string query = "DELETE FROM IG_GriesserSyncMallor2_Lineas WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", idLinea);
                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task<List<IG_GriesserSyncMallor2_Lineas>> GetLineasByPresupuestoAsync(string idLineaPadre)
        {
            var lineas = new List<IG_GriesserSyncMallor2_Lineas>();
            const string query = "SELECT * FROM IG_GriesserSyncMallor2_Lineas WHERE IdLineaPadre = @IdLineaPadre ORDER BY IdLinea";

            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                await connection.OpenAsync();

                using (var reader = await command.ExecuteReaderAsync())
                {
                    while (await reader.ReadAsync())
                    {
                        var linea = new IG_GriesserSyncMallor2_Lineas
                        {
                            IdLineaPadre = reader.GetString("IdLineaPadre"),
                            IdLinea = reader.GetInt32("IdLinea"),
                            pos = reader.IsDBNull("pos") ? (string?)null : reader.GetString("pos"),
                            id_mallorquina_tipo = reader.IsDBNull("id_mallorquina_tipo") ? (int?)null : reader.GetInt32("id_mallorquina_tipo"),
                            cod_mallorquina_tipo = reader.IsDBNull("cod_mallorquina_tipo") ? (string?)null : reader.GetString("cod_mallorquina_tipo"),
                            id_mallorquina_modelo = reader.IsDBNull("id_mallorquina_modelo") ? (int?)null : reader.GetInt32("id_mallorquina_modelo"),
                            cod_mallorquina_modelo = reader.IsDBNull("cod_mallorquina_modelo") ? (string?)null : reader.GetString("cod_mallorquina_modelo"),
                            ancho_hueco = reader.IsDBNull("ancho_hueco") ? (int?)null : reader.GetInt32("ancho_hueco"),
                            alto_hueco = reader.IsDBNull("alto_hueco") ? (int?)null : reader.GetInt32("alto_hueco"),
                            id_mallorquina_esquema = reader.IsDBNull("id_mallorquina_esquema") ? (int?)null : reader.GetInt32("id_mallorquina_esquema"),
                            cod_mallorquina_esquema = reader.IsDBNull("cod_mallorquina_esquema") ? (string?)null : reader.GetString("cod_mallorquina_esquema"),
                            id_mallorquina_tipologia_instalacion = reader.IsDBNull("id_mallorquina_tipologia_instalacion") ? (int?)null : reader.GetInt32("id_mallorquina_tipologia_instalacion"),
                            cod_mallorquina_tipologia_instalacion = reader.IsDBNull("cod_mallorquina_tipologia_instalacion") ? (string?)null : reader.GetString("cod_mallorquina_tipologia_instalacion"),
                            motorizado = reader.IsDBNull("motorizado") ? (bool?)null : reader.GetBoolean("motorizado"),
                            ancho_hoja = reader.IsDBNull("ancho_hoja") ? (int?)null : reader.GetInt32("ancho_hoja"),
                            alto_hoja = reader.IsDBNull("alto_hoja") ? (int?)null : reader.GetInt32("alto_hoja"),
                            precio_por_hoja = reader.IsDBNull("precio_por_hoja") ? (decimal?)null : reader.GetDecimal("precio_por_hoja"),
                            num_hojas = reader.IsDBNull("num_hojas") ? (int?)null : reader.GetInt32("num_hojas"),
                            precio_herraje = reader.IsDBNull("precio_herraje") ? (decimal?)null : reader.GetDecimal("precio_herraje"),
                            precio_incrementos = reader.IsDBNull("precio_incrementos") ? (decimal?)null : reader.GetDecimal("precio_incrementos"),
                            precio_automatismos = reader.IsDBNull("precio_automatismos") ? (decimal?)null : reader.GetDecimal("precio_automatismos"),
                            units = reader.IsDBNull("units") ? (int?)null : reader.GetInt32("units"),
                            total = reader.IsDBNull("total") ? (decimal?)null : reader.GetDecimal("total"),
                            id_automatismo_marca = reader.IsDBNull("id_automatismo_marca") ? (int?)null : reader.GetInt32("id_automatismo_marca"),
                            cod_automatismo_marca = reader.IsDBNull("cod_automatismo_marca") ? (string?)null : reader.GetString("cod_automatismo_marca"),
                            id_automatismo_receptor = reader.IsDBNull("id_automatismo_receptor") ? (int?)null : reader.GetInt32("id_automatismo_receptor"),
                            cod_automatismo_receptor = reader.IsDBNull("cod_automatismo_receptor") ? (string?)null : reader.GetString("cod_automatismo_receptor"),
                            precio_receptor = reader.IsDBNull("precio_receptor") ? (decimal?)null : reader.GetDecimal("precio_receptor"),
                            precio_mandos = reader.IsDBNull("precio_mandos") ? (decimal?)null : reader.GetDecimal("precio_mandos")
                        };
                        lineas.Add(linea);
                    }
                }
            }
            return lineas;
        }

        public async Task<int> GetTotalLineasCountAsync()
        {
            const string query = "SELECT COUNT(*) FROM IG_GriesserSyncMallor2_Lineas";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                await connection.OpenAsync();
                return (int)await command.ExecuteScalarAsync();
            }
        }

        public async Task<int> GetLineasCountByPresupuestoAsync(string idLineaPadre)
        {
            const string query = "SELECT COUNT(*) FROM IG_GriesserSyncMallor2_Lineas WHERE IdLineaPadre = @IdLineaPadre";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                await connection.OpenAsync();
                return (int)await command.ExecuteScalarAsync();
            }
        }
    }
}
