// <auto-generated />
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using GriesserPresuSync.Controllers;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using static GriesserPresuSync.Controllers.MiGriesserMallorquinas;

namespace GriesserPresuSync.Migrations
{
    // ========================================
    // MiGriesserMallorquinas_MandosRepository.cs
    // IG_GriesserSyncMallor2_Mandos - Tabla Tercer Nivel
    // ========================================

    public class MiGriesserMallorquinas_MandosRepository
    {
        private readonly string _connectionString;

        public MiGriesserMallorquinas_MandosRepository(string connectionString)
        {
            _connectionString = connectionString;
        }

        public async Task<List<(string IdLineaPadre, int IdLinea, int IdAutomatismoMando)>> GetAllMandosPksAsync()
        {
            var pks = new List<(string, int, int)>();
            const string query = "SELECT IdLineaPadre, IdLinea, id_automatismo_mando FROM IG_GriesserSyncMallor2_Mandos";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                await connection.OpenAsync();
                using (var reader = await command.ExecuteReaderAsync())
                {
                    while (await reader.ReadAsync())
                    {
                        if (!reader.IsDBNull(0) && !reader.IsDBNull(1) && !reader.IsDBNull(2))
                        {
                            pks.Add((reader.GetString(0), reader.GetInt32(1), reader.GetInt32(2)));
                        }
                    }
                }
            }
            return pks;
        }

        public async Task InsertMandoAsync(IG_GriesserSyncMallor2_Mandos mando)
        {
            const string query = @"INSERT INTO IG_GriesserSyncMallor2_Mandos (
                IdLineaPadre, IdLinea, id_automatismo_mando, cod_automatismo_mando, price, units, total
            ) VALUES (
                @IdLineaPadre, @IdLinea, @id_automatismo_mando, @cod_automatismo_mando, @price, @units, @total
            )";

            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", mando.IdLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", mando.IdLinea);
                command.Parameters.AddWithValue("@id_automatismo_mando", mando.id_automatismo_mando);
                command.Parameters.AddWithValue("@cod_automatismo_mando", (object?)mando.cod_automatismo_mando ?? DBNull.Value);
                command.Parameters.AddWithValue("@price", (object?)mando.price ?? DBNull.Value);
                command.Parameters.AddWithValue("@units", (object?)mando.units ?? DBNull.Value);
                command.Parameters.AddWithValue("@total", (object?)mando.total ?? DBNull.Value);

                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task<bool> ExistsMandoAsync(string idLineaPadre, int idLinea, int idAutomatismoMando)
        {
            const string query = "SELECT COUNT(1) FROM IG_GriesserSyncMallor2_Mandos WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea AND id_automatismo_mando = @id_automatismo_mando";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", idLinea);
                command.Parameters.AddWithValue("@id_automatismo_mando", idAutomatismoMando);
                await connection.OpenAsync();
                var count = (int)await command.ExecuteScalarAsync();
                return count > 0;
            }
        }

        public async Task UpdateMandoAsync(IG_GriesserSyncMallor2_Mandos mando)
        {
            const string query = @"UPDATE IG_GriesserSyncMallor2_Mandos SET 
                cod_automatismo_mando = @cod_automatismo_mando,
                price = @price,
                units = @units,
                total = @total
            WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea AND id_automatismo_mando = @id_automatismo_mando";

            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", mando.IdLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", mando.IdLinea);
                command.Parameters.AddWithValue("@id_automatismo_mando", mando.id_automatismo_mando);
                command.Parameters.AddWithValue("@cod_automatismo_mando", (object?)mando.cod_automatismo_mando ?? DBNull.Value);
                command.Parameters.AddWithValue("@price", (object?)mando.price ?? DBNull.Value);
                command.Parameters.AddWithValue("@units", (object?)mando.units ?? DBNull.Value);
                command.Parameters.AddWithValue("@total", (object?)mando.total ?? DBNull.Value);

                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task DeleteMandosByLineaAsync(string idLineaPadre, int idLinea)
        {
            const string query = "DELETE FROM IG_GriesserSyncMallor2_Mandos WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", idLinea);
                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task DeleteMandosByPresupuestoAsync(string idLineaPadre)
        {
            const string query = "DELETE FROM IG_GriesserSyncMallor2_Mandos WHERE IdLineaPadre = @IdLineaPadre";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task DeleteMandoAsync(string idLineaPadre, int idLinea, int idAutomatismoMando)
        {
            const string query = "DELETE FROM IG_GriesserSyncMallor2_Mandos WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea AND id_automatismo_mando = @id_automatismo_mando";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", idLinea);
                command.Parameters.AddWithValue("@id_automatismo_mando", idAutomatismoMando);
                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        public async Task<List<IG_GriesserSyncMallor2_Mandos>> GetMandosByLineaAsync(string idLineaPadre, int idLinea)
        {
            var mandos = new List<IG_GriesserSyncMallor2_Mandos>();
            const string query = "SELECT * FROM IG_GriesserSyncMallor2_Mandos WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea ORDER BY id_automatismo_mando";

            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", idLinea);
                await connection.OpenAsync();

                using (var reader = await command.ExecuteReaderAsync())
                {
                    while (await reader.ReadAsync())
                    {
                        var mando = new IG_GriesserSyncMallor2_Mandos
                        {
                            IdLineaPadre = reader.GetString("IdLineaPadre"),
                            IdLinea = reader.GetInt32("IdLinea"),
                            id_automatismo_mando = reader.GetInt32("id_automatismo_mando"),
                            cod_automatismo_mando = reader.IsDBNull("cod_automatismo_mando") ? (string?)null : reader.GetString("cod_automatismo_mando"),
                            price = reader.IsDBNull("price") ? (decimal?)null : reader.GetDecimal("price"),
                            units = reader.IsDBNull("units") ? (int?)null : reader.GetInt32("units"),
                            total = reader.IsDBNull("total") ? (decimal?)null : reader.GetDecimal("total")
                        };
                        mandos.Add(mando);
                    }
                }
            }
            return mandos;
        }

        public async Task<List<IG_GriesserSyncMallor2_Mandos>> GetMandosByPresupuestoAsync(string idLineaPadre)
        {
            var mandos = new List<IG_GriesserSyncMallor2_Mandos>();
            const string query = "SELECT * FROM IG_GriesserSyncMallor2_Mandos WHERE IdLineaPadre = @IdLineaPadre ORDER BY IdLinea, id_automatismo_mando";

            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                await connection.OpenAsync();

                using (var reader = await command.ExecuteReaderAsync())
                {
                    while (await reader.ReadAsync())
                    {
                        var mando = new IG_GriesserSyncMallor2_Mandos
                        {
                            IdLineaPadre = reader.GetString("IdLineaPadre"),
                            IdLinea = reader.GetInt32("IdLinea"),
                            id_automatismo_mando = reader.GetInt32("id_automatismo_mando"),
                            cod_automatismo_mando = reader.IsDBNull("cod_automatismo_mando") ? (string?)null : reader.GetString("cod_automatismo_mando"),
                            price = reader.IsDBNull("price") ? (decimal?)null : reader.GetDecimal("price"),
                            units = reader.IsDBNull("units") ? (int?)null : reader.GetInt32("units"),
                            total = reader.IsDBNull("total") ? (decimal?)null : reader.GetDecimal("total")
                        };
                        mandos.Add(mando);
                    }
                }
            }
            return mandos;
        }

        public async Task<int> GetTotalMandosCountAsync()
        {
            const string query = "SELECT COUNT(*) FROM IG_GriesserSyncMallor2_Mandos";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                await connection.OpenAsync();
                return (int)await command.ExecuteScalarAsync();
            }
        }

        public async Task<int> GetMandosCountByLineaAsync(string idLineaPadre, int idLinea)
        {
            const string query = "SELECT COUNT(*) FROM IG_GriesserSyncMallor2_Mandos WHERE IdLineaPadre = @IdLineaPadre AND IdLinea = @IdLinea";
            using (var connection = new SqlConnection(_connectionString))
            using (var command = new SqlCommand(query, connection))
            {
                command.Parameters.AddWithValue("@IdLineaPadre", idLineaPadre);
                command.Parameters.AddWithValue("@IdLinea", idLinea);
                await connection.OpenAsync();
                return (int)await command.ExecuteScalarAsync();
            }
        }
    }
}