// <auto-generated />
using System;
using GriesserPresuSync.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GriesserPresuSync.Migrations
{
    [DbContext(typeof(MiGriesserContext))]
    [Migration("20210111152420_WeinorFamily")]
    partial class WeinorFamily
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GriesserPresuSync.Controllers.MiGriesserContext+IG_Presupuesto_LineaSincronizacion", b =>
                {
                    b.Property<string>("IdLinea")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Articulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BK")
                        .HasColumnType("real");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HL")
                        .HasColumnType("real");

                    b.Property<int>("IdBudget")
                        .HasColumnType("int");

                    b.Property<bool>("IsSincronized")
                        .HasColumnType("bit");

                    b.Property<float>("LargoTapas")
                        .HasColumnType("real");

                    b.Property<int>("NPersianas")
                        .HasColumnType("int");

                    b.Property<string>("NPresupuesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PUnidad")
                        .HasColumnType("real");

                    b.Property<float>("PUnidad2")
                        .HasColumnType("real");

                    b.Property<float>("TEUR")
                        .HasColumnType("real");

                    b.Property<float>("TL")
                        .HasColumnType("real");

                    b.Property<float>("TotalAncho")
                        .HasColumnType("real");

                    b.Property<float>("TotalLargo")
                        .HasColumnType("real");

                    b.Property<float>("TotalSup")
                        .HasColumnType("real");

                    b.Property<int>("TotalTapas")
                        .HasColumnType("int");

                    b.Property<int>("Uni")
                        .HasColumnType("int");

                    b.Property<string>("con_testero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<float?>("importe_automatismos")
                        .HasColumnType("real");

                    b.Property<float?>("importe_color")
                        .HasColumnType("real");

                    b.Property<float?>("importe_incrementos")
                        .HasColumnType("real");

                    b.Property<float>("importe_lineas")
                        .HasColumnType("real");

                    b.Property<float?>("importe_tapas_y_testeros")
                        .HasColumnType("real");

                    b.Property<float?>("importe_tejido")
                        .HasColumnType("real");

                    b.Property<float>("importe_total")
                        .HasColumnType("real");

                    b.Property<float?>("importe_transporte")
                        .HasColumnType("real");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<float>("price_tapa")
                        .HasColumnType("real");

                    b.Property<float>("price_testero")
                        .HasColumnType("real");

                    b.Property<float?>("superficie")
                        .HasColumnType("real");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("weinor_family")
                        .HasColumnType("bit");

                    b.HasKey("IdLinea");

                    b.ToTable("IG_GriesserSyncPresupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
