// <auto-generated />
using System;
using GriesserPresuSync.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GriesserPresuSync.Migrations
{
    [DbContext(typeof(MiGriesserContext))]
    partial class MiGriesserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GriesserPresuSync.Controllers.MiGriesserContext+IG_Presupuesto_LineaSincronizacion", b =>
                {
                    b.Property<string>("IdLinea")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Articulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BK")
                        .HasColumnType("real");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Embalaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HL")
                        .HasColumnType("real");

                    b.Property<int>("IdBudget")
                        .HasColumnType("int");

                    b.Property<bool>("IsSincronized")
                        .HasColumnType("bit");

                    b.Property<float>("LargoTapas")
                        .HasColumnType("real");

                    b.Property<int>("NPersianas")
                        .HasColumnType("int");

                    b.Property<string>("NPresupuesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POS")
                        .HasColumnType("int");

                    b.Property<string>("POS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PUnidad")
                        .HasColumnType("real");

                    b.Property<float>("PUnidad2")
                        .HasColumnType("real");

                    b.Property<float>("TEUR")
                        .HasColumnType("real");

                    b.Property<float>("TL")
                        .HasColumnType("real");

                    b.Property<float>("TotalAncho")
                        .HasColumnType("real");

                    b.Property<float>("TotalLargo")
                        .HasColumnType("real");

                    b.Property<float>("TotalSup")
                        .HasColumnType("real");

                    b.Property<int>("TotalTapas")
                        .HasColumnType("int");

                    b.Property<int>("Uni")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLinea");

                    b.ToTable("IG_GriesserSyncPresupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
